Add troubleshooting/help docs
Chatterino/wiki pull request #10
Opened 2020-10-11 13:47 UTC by alazymeme

Fixes https://github.com/Chatterino/wiki/issues/1
Fixes https://github.com/Chatterino/wiki/issues/5

2020-10-13 13:43 UTC, leon-richardt requested changes
Nice, lots of good points in there. I like it!

2020-10-13 13:43 UTC, leon-richardt commented on docs/Help.md
> +### How do I get the dank supporter badge?
```suggestion
### How do I get the supporter badge?
```

2020-10-13 13:43 UTC, leon-richardt commented on docs/Help.md
> +- Your network may be having issues connecting to braize. Try restarting your PC and router.
I suggest removing the name of the server (`braize`). It does not help users debug the problem and would need to be changed if we ever decide to move the link resolver to a different host.

2020-10-13 13:43 UTC, leon-richardt commented on docs/Help.md
> +- Try running Chatterino in administrator mode.
Windows-only instructions

2020-10-13 13:43 UTC, leon-richardt commented on docs/Help.md
> +- Try running Chatterino in administrator mode.
Windows-only instructions

2020-10-13 13:43 UTC, leon-richardt commented on docs/Help.md
> +This will however work with most chatbots, as they simply take you being connected to chat as "watching the stream"
```suggestion
This will however work with most chatbots, as they simply take you being connected to chat as "watching the stream".
```

2020-10-13 13:43 UTC, leon-richardt commented on docs/Help.md
> +- If you're trying to type in a chat where there are a lot of active chatters, then your message may be dropped by Twitch's chat servers (due to the volume )
```suggestion
- If you're trying to type in a chat where there are a lot of active chatters, then your message may be dropped by Twitch's chat servers (due to the volume).
```

2020-10-13 13:43 UTC, leon-richardt commented on docs/Help.md
> +- If an alt account has been banned in that chat, you have likely been shadowbanned by Twitch in that channel. Preventing any of your other accounts from speaking in that channel.
```suggestion
- If an alt account has been banned in that chat, you have likely been shadowbanned by Twitch in that channel, preventing any of your other accounts from speaking in that channel.
```

2020-10-13 13:43 UTC, leon-richardt commented on docs/Help.md
> +The most likely issue here is due to the large amount of channels you are connected to. The maximum channel limit is usually around the 100 mark, but may differ from user to user.
Maybe also mention that user should try closing the number of splits in Chatterino?

2020-10-14 00:58 UTC, alazymeme commented on docs/Help.md
> +- If an alt account has been banned in that chat, you have likely been shadowbanned by Twitch in that channel. Preventing any of your other accounts from speaking in that channel.
```suggestion
- If an alt account has been banned in that chat, you have likely been shadowbanned by Twitch in that channel. Which prevents any of your other accounts from speaking in that channel.
```

2020-10-15 18:00 UTC, fourtf commented
Looks good to me 👍 Thank you for your contribution!

2020-10-15 18:00 UTC, merged

2020-10-15 18:06 UTC, leon-richardt commented
305d350 broke the link to the Visual C++ Redistributables by the way ([line 9](https://github.com/Chatterino/wiki/pull/10/files#diff-806d0920ce9a20e3a4bf5429a55bbbcf486f4062c5e949b8216d41eb5520964bR9) in `Help.md`)

2020-10-15 21:45 UTC, alazymeme commented
> [305d350](https://github.com/Chatterino/wiki/commit/305d350a8b603278e9b1eff3fe3ec91176239dd5) broke the link to the Visual C++ Redistributables by the way ([line 9](https://github.com/Chatterino/wiki/pull/10/files#diff-806d0920ce9a20e3a4bf5429a55bbbcf486f4062c5e949b8216d41eb5520964bR9) in `Help.md`)

I see this, I might need to directly add it into the line.