Add Documentation for disabling your chatterino badge
Chatterino/wiki pull request #153
Opened 2021-12-27 20:54 UTC by killertofus

2021-12-27 21:00 UTC, Mm2PL commented
Please don't PR unrelated changes like 8293c9e. Also PRing from master (or more generally the main branch) is a bad idea because of possibility residue commits, which is what I think happened in this case.

2021-12-27 21:10 UTC, Mm2PL requested changes
Here is my take on this :)

2021-12-27 21:10 UTC, Mm2PL commented on docs/Help.md
> +login to the [manage page] (https://manage.chatterino.com/) and click on disable your Chatterino badge
- New line at the end was missing.
 - Fix up grammar.
 - Stray space in markdown link syntax.

```suggestion
### How do I disable the supporter badge?
Log in to the [badge manager](https://manage.chatterino.com/) and click on *Disable My Chatterino Badge*.

```

2021-12-27 21:29 UTC, zneix commented
I actually talked to fourtf weeks ago and he has specifically asked me to not officially announce this yet - he said he's not certain about whether the service can stay as it is currently, it's his microservice and until he decides, this is not officially "out" just yet.

2021-12-27 21:30 UTC, fourtf commented
Seems fine with me

2021-12-27 21:31 UTC, zneix commented
if you say so

2021-12-28 14:17 UTC, pajlada approved these changes

2021-12-28 14:17 UTC, merged