CtrlV.link image upload integration
Chatterino/wiki pull request #164
Opened 2022-01-15 20:54 UTC by lukyer

Adding docs info about requested ctrlv.link/ctrlv.cz image uploader integration.
Discussion: https://github.com/Chatterino/chatterino2/discussions/3513

I'm open to any reordering you might prefer. I put it as a first item because this one doesn't require any authentication/accounts nor self-hosting.

2022-01-15 21:50 UTC, Felanbird commented
Immediate issue I notice is since you don't use a direct link, [Chatterino/api](https://github.com/Chatterino/api/) cannot resolve your website for thumbnails, all of our existing examples "just work" because of direct links/opengraph tags. 
![image](https://user-images.githubusercontent.com/41973452/149638060-917e33ec-e9c5-4e5f-98aa-a2dbcc56f4c6.png)

My opinion on the best approach for this would be just sending us the entire direct link, since the direct link includes the date and is already resolved by the api.
![image](https://user-images.githubusercontent.com/41973452/149638791-1c9775a7-c7cb-470c-b7e1-c12cd689df2a.png)


examples that just work
![image](https://user-images.githubusercontent.com/41973452/149637906-2179d6e3-d7e4-4525-9b56-1c3326f24bff.png)
![image](https://user-images.githubusercontent.com/41973452/149637870-eb533f98-5214-401e-844a-a688f0cc3ed7.png)
imgur
![image](https://user-images.githubusercontent.com/41973452/149637940-50bb92c2-3c71-4374-9099-4adaedec695f.png)
fourtf/i self host
![image](https://user-images.githubusercontent.com/41973452/149638356-1fdea160-04a5-45fc-ae49-ef21b7f7211c.png)
gyazo as extra example
![image](https://user-images.githubusercontent.com/41973452/149638042-10b8a409-65b8-4bad-977e-106469ed042a.png)

2022-01-15 22:32 UTC, lukyer commented
@Felanbird ah, thanks! This functionality (opengraph thumbnails with smaller size) is implemented. I have just whitelisted Chatterino client. Please try it again now. It looks good to me.

2022-01-15 22:38 UTC, Felanbird commented
> @Felanbird ah, thanks! This functionality (opengraph thumbnails with smaller size) is implemented. I have just whitelisted Chatterino client. Please try it again now. It looks good to me.

The noted issue has been resolved 👍

2022-01-16 04:25 UTC, ALazyMeme requested changes

2022-01-16 04:25 UTC, ALazyMeme commented on docs/Image Uploader.md
> +However, popular hosts like [imgur.com](https://imgur.com), [s-ul.eu](https://s-ul.eu) and [ctrlv.link](https://ctrlv.link) are supported. Scroll down to see example cofiguration.
I'm not so sure about this edit. i.nuuls.com isn't included in this list, and it's a highly used website by a lot of users on Twitch.

2022-01-16 04:25 UTC, ALazyMeme commented on docs/Image Uploader.md
> +
New websites have been added to the bottom in past PRs. I think we should add this to the bottom as opposed to the top.

2022-01-16 11:19 UTC, gempir commented
Your website is missing something basic as a legal notice.
No privacy policy as far as I can see either.

The way you are using PHP makes me also think you are not using basic modern patterns like the [front controller pattern](https://en.wikipedia.org/wiki/Front_controller)

And since your software is closed source nobody can validate its security besides you. 

That makes me strongly dislike just adding your website to the Chatterino wiki, it's not supposed to be an ad space.

2022-01-16 11:22 UTC, pajlada commented
The way I envision new image upload integrations to be added is through enough community members asking Chatterino contributors through the Discussions tag in the [main repo](https://github.com/Chatterino/chatterino2), or through our Discord, about how to use it with Chatterino.

Having all discussion created by the owner of the closed-source/commercial image uploader me and other contributors haven't heard of gives me strange vibes, which is why I'm closing this PR.

Feel free to continue to use this PR or the [discussion you created](https://github.com/Chatterino/chatterino2/discussions/3513) if you have any questions about this decision (or reach out on the Discord that you can find top-right of https://chatterino.com/)

2022-01-16 11:22 UTC, closed without merging

2022-01-16 11:46 UTC, lukyer commented
> Your website is missing something basic as a legal notice. No privacy policy as far as I can see either.

Privacy notice minimum required is in the footer. The reason why people use this well established service is mainly because it is easy to use and not bloated with nonsenses. 

> The way you are using PHP makes me also think you are not using basic modern patterns like the [front controller pattern](https://en.wikipedia.org/wiki/Front_controller)

Sorry but this is absolutely offtopic. I now what suits best this kind of service and technology. You may prefer to choose any design patterns by trends but it doesn't mean everyone does. 

> And since your software is closed source nobody can validate its security besides you.

If you want to validate security of the service, feel free to do another pentest. I'm happy to discuss any findings. We are doing blackbox pentests regularly. 

> That makes me strongly dislike just adding your website to the Chatterino wiki, it's not supposed to be an ad space.

I absolutely don't get your attitude here. I was asked by twitch users to add this integration. I'm making such open source integrations when multiple people are asking for it. This time I set up my very first twitch account to investigate it. I didn't know Chatterino SW before at all.


I already regret trying to contribute to this open source project.

2022-01-16 11:57 UTC, lukyer commented
> The way I envision new image upload integrations to be added is through enough community members asking Chatterino contributors through the Discussions tag in the [main repo](https://github.com/Chatterino/chatterino2), or through our Discord, about how to use it with Chatterino.

Please mention it somewhere - I was looking for correct way how to contribute with these user requests. If I knew this I would ask requesters to start some discussion thread here. Maybe someone in the future will be in similar situation.

> Having all discussion created by the owner of the closed-source/commercial image uploader me and other contributors haven't heard of gives me strange vibes, which is why I'm closing this PR.

Let me cite this part of my yesterday's discussion about what Chatterino is:
"..jedná se o asi nejrozšířenější klient na twitch v zahraničí i v česku.."

> Feel free to continue to use this PR or the [discussion you created](https://github.com/Chatterino/chatterino2/discussions/3513) if you have any questions about this decision (or reach out on the Discord that you can find top-right of https://chatterino.com/)

Just wanted to justify for the record some misinformation posted here. I'm not interested in any more contributions here.

2022-01-16 11:58 UTC, gempir commented
My comments about development decisions are off topic I agree, sorry. 

I just would like some more information how you handle customer data. 
Here are some pointers https://gdpr.eu/privacy-notice/

2022-02-09 13:47 UTC, subzero1177 commented
Hello, I was told to ask here about my configuration described in https://github.com/Chatterino/chatterino2/issues/3552
How can I set up the integration? Thanks in advance.

2022-02-09 14:06 UTC, LosFarmosCTL commented
> Hello, I was told to ask here about my configuration described in [Chatterino/chatterino2#3552](https://github.com/Chatterino/chatterino2/issues/3552)
> How can I set up the integration? I see many links around in channels I'm in. So I'm curious how to set it up? Thanks in advance.

There is a wiki for chatterino with a dedicated page about [how to set custom image uploaders](https://wiki.chatterino.com/Image%20Uploader/). Also just scrolling through chatterino's settings for a maximum of 2 minutes, under "External tools" you would have found a form that exactly matches the screenshot you linked yourself, where you can just fill in the information from that screenshot.

And to reiterate, this is not a ctrlv support forum, if anything doesn't work with that configuration, no one here can do anything about that, ask the creator for help.

2022-02-09 14:12 UTC, subzero1177 commented
Hey, that's the missing bit! I combined those two instructions and It seems to work now, thanks a lot! 🥳