Added default folder and more troubleshooting docs
Chatterino/wiki pull request #24
Opened 2020-11-26 00:45 UTC by zneix

We refer to "appdata folder" as "Chatterino folder" and there are also troubleshooting steps for Chatterino not saving user settings.
Added missing dots to few sentence endings as well.

2020-11-26 08:45 UTC, alazymeme requested changes

2020-11-26 08:45 UTC, alazymeme commented on docs/Help.md
> +
No need for this extra space

2020-11-26 08:45 UTC, alazymeme commented on docs/Help.md
> +### Where is Chatterino folder located?
There are technically two chatterino folders. Maybe `Where is my Chatterino data folder located?` or something similar.

2020-11-26 08:45 UTC, alazymeme commented on docs/Help.md
> +Navigate to [Chatterino folder](#where-is-chatterino-folder-located) and remove corresponding folders.
I'm not sure about this, it's making a simple step more complicated for no reason. Where a simple troubleshooting step such as "Delete your Chatterino cache" can be used and easily found, they now have to go to two different locations to find out what they have to delete.

2020-12-12 11:32 UTC, pajlada requested changes

2020-12-12 11:32 UTC, pajlada commented on docs/Help.md
> +### Where is Chatterino folder located?
phrasing, change to "the Chatterino folder" or "my Chatterino folder" - not sure which is best, but as long as we're consistent it should be all good

2020-12-12 11:32 UTC, pajlada commented on docs/Help.md
> +Navigate to [Chatterino folder](#where-is-chatterino-folder-located) and remove corresponding folders.
make this babyproof

2021-01-31 11:23 UTC, pajlada approved these changes

2021-01-31 11:25 UTC, merged